#!/usr/bin/env bash

JDK_VERSION="21-jdk"

read -r -d '' PLAY_VERSIONS <<-LIST
1.7.1
1.8.0
LIST

read -r -d '' WARN_HEADER <<-EOM
#
# AUTO-GENERATED - DO NOT EDIT THIS FILE
# 
# GENERATED: $(date -u)
#
EOM

OLD_PWD=$(pwd)

for PLAY_VERSION in $(echo $PLAY_VERSIONS); do
  IMAGE_VERSION=${PLAY_VERSION}-${JDK_VERSION}

  export PLAY_VERSION
  export JDK_VERSION

  rm -Rf ${IMAGE_VERSION}
  mkdir -p ${IMAGE_VERSION}
  echo "${WARN_HEADER}" > ${IMAGE_VERSION}/Dockerfile
  cat Dockerfile >> ${IMAGE_VERSION}/Dockerfile

  cd ${IMAGE_VERSION}
  docker buildx build \
    --push \
    --platform=linux/arm64,linux/arm64/v8,linux/amd64 \
    --build-arg PLAY_VERSION \
    --build-arg JDK_VERSION \
    -t phaus/play:${IMAGE_VERSION} .
  docker run --rm -it phaus/play:${IMAGE_VERSION}
  cd ${OLD_PWD}
done

docker images phaus/play
