#!/usr/bin/env bash

JDK_VERSION="openjdk11"

read -r -d '' PLAY_VERSIONS <<-LIST
1.2.5.6
1.2.6.2
1.2.7.2
1.3.4
1.4.6
1.5.3
LIST

read -r -d '' WARN_HEADER <<-EOM
#
# AUTO-GENERATED - DO NOT EDIT THIS FILE
# 
# GENERATED: $(date -u)
#
EOM

OLD_PWD=$(pwd)

for PLAY_VERSION in $(echo $PLAY_VERSIONS); do
  IMAGE_VERSION=${PLAY_VERSION}-${JDK_VERSION}

  export PLAY_VERSION
  export JDK_VERSION

  rm -Rf ${IMAGE_VERSION}
  mkdir -p ${IMAGE_VERSION}
  echo "${WARN_HEADER}" > ${IMAGE_VERSION}/Dockerfile
  cat Dockerfile >> ${IMAGE_VERSION}/Dockerfile

  cd ${IMAGE_VERSION}
  docker build --pull --build-arg PLAY_VERSION --build-arg JDK_VERSION -t phaus/play:${IMAGE_VERSION} .
  docker run --rm -it phaus/play:${IMAGE_VERSION}
  docker push phaus/play:${IMAGE_VERSION}
  cd ${OLD_PWD}
done

docker images phaus/play
